services:
  - type: web
    name: Alrahma-1
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: CRON_SECRET
        sync: false
      - key: RENEWAL_REMINDER_DAYS
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: PAYPAL_MODE
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_WEBHOOK_ID
        sync: false
      - key: ADMIN_JWT_ACCESS_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: ADMIN_IP_WHITELIST
        sync: false