import { TEACHERS } from "../src/data/marketing/teachers.js";

export const seoRoutes = [
  "/",
  "/courses",
  "/courses/quran",
  "/courses/ijazah",
  "/courses/islamic-studies",
  "/courses/arabic",
  "/tools",
  "/tools/quran-reader",
  "/tools/adhkar",
  "/tools/hadith",
  "/tools/prayer",
  "/tools/prayer-times",
  "/tools/qibla",
  "/tools/islamic-calendar",
  "/tools/verse-of-the-day",
  "/tools/tasbeeh",
  "/tools/arabic-alphabet",
  "/tools/tajweed-checker",
  "/tools/hifz-review",
  "/resources",
  "/resources/blog",
  "/resources/faq",
  "/academy",
  "/academy/about",
  "/academy/teachers",
  ...TEACHERS.map((teacher) => `/academy/teachers/${teacher.id}`),
  "/academy/privacy",
  "/academy/terms",
  "/academy/refund-policy",
  "/enroll",
];