import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import { cleanup } from '@testing-library/react';
import { useFullPageEnvironment, mountFullPage, headMeta } from './utils/fullPageRender';
import Home from '../pages/Home';
import AboutPage from '../pages/About';
import CoursesHub from '../pages/hubs/CoursesHub';
import CoursesQuran from '../pages/hubs/CoursesQuran';
import CoursesArabic from '../pages/hubs/CoursesArabic';
import AcademyHub from '../pages/hubs/AcademyHub';
import { HOME_SEO_TEXT } from '../i18n/home/seo';
import { COURSES_SEO_TEXT } from '../i18n/courses/seo';
import { ACADEMY_SEO_TEXT } from '../i18n/academy/seo';
import { PAGE_HEADING_TEXT } from '../i18n/about/pageHeading';
import { FOUNDER_STORY_TEXT } from '../i18n/about/founderStory';
import { LEVEL_QUIZ_TEXT } from '../i18n/home/levelQuiz';
import { ISNAD_CHAIN_TEXT } from '../i18n/home/isnadChain';
import { HOME_LEAKED_STRINGS_TEXT, COURSE_OPTION_LABELS_TEXT } from '../i18n/home/leakedStrings';
import { COUNTRY_NAMES_TEXT } from '../i18n/home/countries';

// French Localization Batch 1A: EN and AR must stay byte-for-byte what they
// were before French was added to these six pages. The baseline fixture was
// generated from origin/main @ 79561a4 (before any Batch 1A change) with
// FR_BATCH1A_WRITE_BASELINE=1, and is compared here, never regenerated by
// a normal run:
//   - the en/ar entries of every text module Batch 1A touched, and
//   - the fully rendered EN and AR page (every section mounted): document
//     title, meta description, OG tags, <html lang/dir>, and a SHA-256 of the
//     whole <body> markup, so any changed text, aria-label or attribute fails.

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BASELINE_PATH = path.join(__dirname, 'fixtures', 'fr-batch1a-en-ar-baseline.json');
const WRITE = process.env.FR_BATCH1A_WRITE_BASELINE === '1';

const PAGES = [
  ['home', '/', Home],
  ['courses', '/courses', CoursesHub],
  ['coursesQuran', '/courses/quran', CoursesQuran],
  ['coursesArabic', '/courses/arabic', CoursesArabic],
  ['academy', '/academy', AcademyHub],
  ['about', '/academy/about', AboutPage],
];

const MODULES = {
  HOME_SEO_TEXT,
  COURSES_SEO_TEXT_hub: COURSES_SEO_TEXT.hub,
  COURSES_SEO_TEXT_quran: COURSES_SEO_TEXT.quran,
  COURSES_SEO_TEXT_arabic: COURSES_SEO_TEXT.arabic,
  ACADEMY_SEO_TEXT,
  PAGE_HEADING_TEXT,
  FOUNDER_STORY_TEXT,
  LEVEL_QUIZ_TEXT,
  ISNAD_CHAIN_TEXT,
  HOME_LEAKED_STRINGS_TEXT,
  COURSE_OPTION_LABELS_TEXT,
  COUNTRY_NAMES_TEXT,
};

function enAr(mod) {
  return JSON.parse(JSON.stringify({ en: mod.en, ar: mod.ar ?? null }));
}

async function renderPage(urlPath, Page) {
  await mountFullPage(urlPath, Page);
  const html = document.body.innerHTML;
  return {
    title: document.title,
    description: headMeta('meta[name="description"]'),
    ogTitle: headMeta('meta[property="og:title"]'),
    ogDescription: headMeta('meta[property="og:description"]'),
    htmlLang: document.documentElement.lang,
    htmlDir: document.documentElement.dir,
    bodySha256: crypto.createHash('sha256').update(html).digest('hex'),
    bodyLength: html.length,
    deferredSectionsMounted: !!document.querySelector('.isnad__quote, .founder, .hub-cards, .hub-feature-row'),
  };
}

useFullPageEnvironment();

async function currentSnapshot() {
  const pages = {};
  for (const [key, enPath, Page] of PAGES) {
    const arPath = enPath === '/' ? '/ar/' : `/ar${enPath}`;
    pages[key] = { en: await renderPage(enPath, Page) };
    cleanup();
    pages[key].ar = await renderPage(arPath, Page);
    cleanup();
  }
  const modules = Object.fromEntries(Object.entries(MODULES).map(([k, v]) => [k, enAr(v)]));
  return { baseline: 'origin/main@79561a4', modules, pages };
}

describe('French Batch 1A leaves English and Arabic byte-identical', () => {
  if (WRITE) {
    it('writes the EN/AR baseline fixture', async () => {
      fs.mkdirSync(path.dirname(BASELINE_PATH), { recursive: true });
      fs.writeFileSync(BASELINE_PATH, `${JSON.stringify(await currentSnapshot(), null, 2)}\n`);
    }, 60000);
    return;
  }

  const baseline = JSON.parse(fs.readFileSync(BASELINE_PATH, 'utf8'));

  it('en/ar entries of every touched text module equal the baseline', () => {
    for (const [name, mod] of Object.entries(MODULES)) {
      expect(enAr(mod), name).toEqual(baseline.modules[name]);
    }
  });

  it('every rendered EN and AR page (metadata + full body markup) equals the baseline', async () => {
    const now = await currentSnapshot();
    for (const [key] of PAGES) {
      expect(now.pages[key].en, `${key} (en)`).toEqual(baseline.pages[key].en);
      expect(now.pages[key].ar, `${key} (ar)`).toEqual(baseline.pages[key].ar);
    }
  }, 60000);
});
