import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { describe, it, expect, vi } from 'vitest';
import { cleanup } from '@testing-library/react';
import { useFullPageEnvironment } from './utils/fullPageRender';
import { BATCH_1D, pageMeta } from './utils/frenchBatch1dStates';

// French Localization Batch 1D: English and Arabic output of every Batch 1D
// template must stay byte-for-byte what it was on origin/main @ 1a8d498
// (after Batch 1C, before Batch 1D). The baseline fixture was generated from
// that commit with FR_BATCH1D_WRITE_BASELINE=1 and is compared here, never
// regenerated by a normal run.
//
// States: /resources (hub), /tools (hub, the free-trial modal open, both
// validation messages, a failed and a successful trial request — the API is
// mocked, nothing is sent), /tools/prayer (the prayer-tools hub — its own
// card titles/descriptions only; the deferred tools behind its links are
// not touched), and /resources/blog (loading, load-error and the empty
// listing — the only states production can show with 0 posts).

vi.mock('../api/blogApi', () => ({ getBlogPosts: vi.fn(), getBlogPost: vi.fn() }));
vi.mock('../api/contentApi', async (orig) => ({ ...(await orig()), submitTrial: vi.fn() }));

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BASELINE_PATH = path.join(__dirname, 'fixtures', 'fr-batch1d-en-ar-baseline.json');
const WRITE = process.env.FR_BATCH1D_WRITE_BASELINE === '1';

const sha = (s) => crypto.createHash('sha256').update(s).digest('hex');

useFullPageEnvironment();

async function snapshot(page, prefix, mocks) {
  const states = {};
  await page.run(prefix, async (name) => {
    const { jsonLd, ...meta } = pageMeta();
    states[name] = { ...meta, jsonLd: sha(jsonLd.join('\n')), body: sha(document.body.innerHTML) };
  }, mocks);
  cleanup();
  return states;
}

async function currentSnapshot() {
  const { getBlogPosts } = await import('../api/blogApi');
  const { submitTrial } = await import('../api/contentApi');
  const mocks = { getBlogPosts, submitTrial };
  const pages = {};
  for (const page of BATCH_1D) {
    pages[page.key] = { en: await snapshot(page, '', mocks), ar: await snapshot(page, '/ar', mocks) };
  }
  return { baseline: 'origin/main@1a8d498', pages };
}

describe('French Batch 1D leaves English and Arabic byte-identical', () => {
  if (WRITE) {
    it('writes the EN/AR baseline fixture', async () => {
      fs.mkdirSync(path.dirname(BASELINE_PATH), { recursive: true });
      fs.writeFileSync(BASELINE_PATH, `${JSON.stringify(await currentSnapshot(), null, 2)}\n`);
    }, 120000);
    return;
  }

  const baseline = JSON.parse(fs.readFileSync(BASELINE_PATH, 'utf8'));

  it('every EN and AR state of every Batch 1D template (metadata, JSON-LD, full body markup) equals the baseline', async () => {
    const now = await currentSnapshot();
    expect(Object.keys(now.pages)).toEqual(Object.keys(baseline.pages));
    for (const { key } of BATCH_1D) {
      expect(now.pages[key].en, `${key} (en)`).toEqual(baseline.pages[key].en);
      expect(now.pages[key].ar, `${key} (ar)`).toEqual(baseline.pages[key].ar);
    }
  }, 120000);
});
