import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import { cleanup, fireEvent, act } from '@testing-library/react';
import { useFullPageEnvironment, mountFullPage, headMeta } from './utils/fullPageRender';
import CourseIjazah from '../pages/CourseIjazah';
import CourseIslamicStudies from '../pages/CourseIslamicStudies';

// French Localization Batch 1B: English and Arabic /courses/ijazah and
// /courses/islamic-studies must stay byte-for-byte what they were on
// origin/main @ 2e43bb4 (after Batch 1A, before Batch 1B). The baseline
// fixture was generated from that commit with FR_BATCH1B_WRITE_BASELINE=1
// and is compared here, never regenerated by a normal run.
//
// Every interactive state is covered: the page as loaded, each curriculum
// stage / module opened in turn, and every book card opened. For each state
// the SHA-256 of the whole <body> markup is recorded, plus the document
// title, meta description, OG tags, <html lang/dir> and the JSON-LD.

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BASELINE_PATH = path.join(__dirname, 'fixtures', 'fr-batch1b-en-ar-baseline.json');
const WRITE = process.env.FR_BATCH1B_WRITE_BASELINE === '1';

const PAGES = [
  ['ijazah', '/courses/ijazah', CourseIjazah],
  ['islamicStudies', '/courses/islamic-studies', CourseIslamicStudies],
];

const sha = (s) => crypto.createHash('sha256').update(s).digest('hex');

async function click(el) {
  fireEvent.click(el);
  await act(async () => {});
}

async function snapshotPage(urlPath, Page) {
  await mountFullPage(urlPath, Page);
  const states = { initial: sha(document.body.innerHTML) };
  const stageHeaders = [...document.querySelectorAll('.cl__stage-header')];
  for (let i = 0; i < stageHeaders.length; i += 1) {
    await click(document.querySelectorAll('.cl__stage-header')[i]);
    states[`stage${i}`] = sha(document.body.innerHTML);
  }
  for (const trigger of document.querySelectorAll('.cl__book-trigger')) await click(trigger);
  states.allBooksOpen = sha(document.body.innerHTML);
  const snap = {
    title: document.title,
    description: headMeta('meta[name="description"]'),
    ogTitle: headMeta('meta[property="og:title"]'),
    ogDescription: headMeta('meta[property="og:description"]'),
    htmlLang: document.documentElement.lang,
    htmlDir: document.documentElement.dir,
    jsonLd: [...document.head.querySelectorAll('script[type="application/ld+json"]')].map((s) => s.textContent),
    stageCount: stageHeaders.length,
    bookCount: document.querySelectorAll('.cl__book-trigger').length,
    states,
  };
  cleanup();
  return snap;
}

useFullPageEnvironment();

async function currentSnapshot() {
  const pages = {};
  for (const [key, enPath, Page] of PAGES) {
    pages[key] = { en: await snapshotPage(enPath, Page), ar: await snapshotPage(`/ar${enPath}`, Page) };
  }
  return { baseline: 'origin/main@2e43bb4', pages };
}

describe('French Batch 1B leaves English and Arabic byte-identical', () => {
  if (WRITE) {
    it('writes the EN/AR baseline fixture', async () => {
      fs.mkdirSync(path.dirname(BASELINE_PATH), { recursive: true });
      fs.writeFileSync(BASELINE_PATH, `${JSON.stringify(await currentSnapshot(), null, 2)}\n`);
    }, 60000);
    return;
  }

  const baseline = JSON.parse(fs.readFileSync(BASELINE_PATH, 'utf8'));

  it('every EN and AR state of both pages (metadata, JSON-LD, full body markup) equals the baseline', async () => {
    const now = await currentSnapshot();
    for (const [key] of PAGES) {
      expect(now.pages[key].en, `${key} (en)`).toEqual(baseline.pages[key].en);
      expect(now.pages[key].ar, `${key} (ar)`).toEqual(baseline.pages[key].ar);
    }
  }, 60000);
});
