import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { describe, it, expect, vi } from 'vitest';
import { cleanup } from '@testing-library/react';
import { useFullPageEnvironment } from './utils/fullPageRender';
import { BATCH_1C, pageMeta } from './utils/frenchBatch1cStates';
import { submitEnrollment } from '../api/enrollmentApi';

// French Localization Batch 1C: English and Arabic output of every Batch 1C
// template must stay byte-for-byte what it was on origin/main @ 8f8b014
// (after Batch 1B, before Batch 1C). The baseline fixture was generated from
// that commit with FR_BATCH1C_WRITE_BASELINE=1 and is compared here, never
// regenerated by a normal run.
//
// Every state the shared driver reaches is covered (teacher filters and
// bios, all 11 profiles and the unknown-id page, every FAQ item, every
// enroll step, validation message, plan, failure and success screen, the
// legal pages with and without the analytics section, the cookie banner).
// For each state: the document title, description, OG/Twitter tags and
// <html lang/dir>, plus the SHA-256 of the JSON-LD and of the whole <body>
// markup.

vi.mock('../api/enrollmentApi', () => ({ submitEnrollment: vi.fn() }));

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BASELINE_PATH = path.join(__dirname, 'fixtures', 'fr-batch1c-en-ar-baseline.json');
const WRITE = process.env.FR_BATCH1C_WRITE_BASELINE === '1';

// The enroll form shows the machine's own time zone; hash it out so the
// baseline does not depend on where the tests run.
const TZ = Intl.DateTimeFormat().resolvedOptions().timeZone;
const sha = (s) => crypto.createHash('sha256').update(s.split(TZ).join('<TZ>')).digest('hex');

useFullPageEnvironment();

async function snapshot(page, prefix) {
  const states = {};
  await page.run(prefix, async (name) => {
    const { jsonLd, ...meta } = pageMeta();
    states[name] = { ...meta, jsonLd: sha(jsonLd.join('\n')), body: sha(document.body.innerHTML) };
  }, submitEnrollment);
  cleanup();
  return states;
}

async function currentSnapshot() {
  const pages = {};
  for (const page of BATCH_1C) {
    pages[page.key] = { en: await snapshot(page, ''), ar: await snapshot(page, '/ar') };
  }
  return { baseline: 'origin/main@8f8b014', pages };
}

describe('French Batch 1C leaves English and Arabic byte-identical', () => {
  if (WRITE) {
    it('writes the EN/AR baseline fixture', async () => {
      fs.mkdirSync(path.dirname(BASELINE_PATH), { recursive: true });
      fs.writeFileSync(BASELINE_PATH, `${JSON.stringify(await currentSnapshot(), null, 2)}\n`);
    }, 120000);
    return;
  }

  const baseline = JSON.parse(fs.readFileSync(BASELINE_PATH, 'utf8'));

  it('every EN and AR state of every Batch 1C template (metadata, JSON-LD, full body markup) equals the baseline', async () => {
    const now = await currentSnapshot();
    expect(Object.keys(now.pages)).toEqual(Object.keys(baseline.pages));
    for (const { key } of BATCH_1C) {
      expect(now.pages[key].en, `${key} (en)`).toEqual(baseline.pages[key].en);
      expect(now.pages[key].ar, `${key} (ar)`).toEqual(baseline.pages[key].ar);
    }
  }, 120000);
});
