import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { describe, it, expect, vi } from 'vitest';
import { cleanup } from '@testing-library/react';
import { useFullPageEnvironment } from './utils/fullPageRender';
import { BATCH_1E, pageMeta } from './utils/frenchBatch1eStates';

// French Localization Batch 1E: English and Arabic output of every Batch 1E
// template must stay byte-for-byte what it was on origin/main @ 8ccc963
// (after Batch 1D, before Batch 1E). The baseline fixture was generated
// from that commit with FR_BATCH1E_WRITE_BASELINE=1 and is compared here,
// never regenerated by a normal run.
//
// No live network call, geolocation prompt, microphone or carried-over
// date/localStorage value is used: fetchPrayerCity and the hadith CDN fetch
// are mocked with a fixed fixture; jsdom has no navigator.geolocation, so
// the "no location, search prominent" state is reached natively.

vi.mock('../utils/islamicToolsUtils', async (orig) => ({
  ...(await orig()),
  fetchPrayerCity: vi.fn(),
  fetchPrayerCoords: vi.fn(),
  fetchMonth: vi.fn(),
}));

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BASELINE_PATH = path.join(__dirname, 'fixtures', 'fr-batch1e-en-ar-baseline.json');
const WRITE = process.env.FR_BATCH1E_WRITE_BASELINE === '1';

const sha = (s) => crypto.createHash('sha256').update(s).digest('hex');

useFullPageEnvironment();

async function snapshot(page, prefix, mocks) {
  const states = {};
  await page.run(prefix, async (name) => {
    states[name] = { ...pageMeta(), body: sha(document.body.innerHTML) };
  }, mocks);
  cleanup();
  return states;
}

async function currentSnapshot() {
  const { fetchPrayerCity } = await import('../utils/islamicToolsUtils');
  const pages = {};
  for (const page of BATCH_1E) {
    // Re-stubbed fresh for every page: never leaves the real global `fetch`
    // exposed even briefly (fullPageRender's own environment already stubs
    // it to reject, but the hadith driver needs its own resolving mock).
    const fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);
    const mocks = { fetchPrayerCity, fetchMock };
    pages[page.key] = { en: await snapshot(page, '', mocks), ar: await snapshot(page, '/ar', mocks) };
  }
  return { baseline: 'origin/main@8ccc963', pages };
}

describe('French Batch 1E leaves English and Arabic byte-identical', () => {
  if (WRITE) {
    it('writes the EN/AR baseline fixture', async () => {
      fs.mkdirSync(path.dirname(BASELINE_PATH), { recursive: true });
      fs.writeFileSync(BASELINE_PATH, `${JSON.stringify(await currentSnapshot(), null, 2)}\n`);
    }, 120000);
    return;
  }

  const baseline = JSON.parse(fs.readFileSync(BASELINE_PATH, 'utf8'));

  it('every EN and AR state of every Batch 1E template (metadata, full body markup) equals the baseline', async () => {
    const now = await currentSnapshot();
    expect(Object.keys(now.pages)).toEqual(Object.keys(baseline.pages));
    for (const { key } of BATCH_1E) {
      expect(now.pages[key].en, `${key} (en)`).toEqual(baseline.pages[key].en);
      expect(now.pages[key].ar, `${key} (ar)`).toEqual(baseline.pages[key].ar);
    }
  }, 120000);
});
