import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import { cleanup, fireEvent, act } from '@testing-library/react';
import { useFullPageEnvironment, mountFullPage, headMeta } from './utils/fullPageRender';
import CourseIjazah from '../pages/CourseIjazah';

// Italian Ijazah Content Batch: English, Arabic and French /courses/ijazah
// must stay byte-for-byte what they were on origin/main @ 185fe95 (before
// this batch). The baseline fixture was generated from that commit with
// IT_IJAZAH_WRITE_BASELINE=1 and is compared here, never regenerated by a
// normal run. Every interactive state is covered (as loaded, each stage
// opened, every book opened), including metadata and JSON-LD.

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BASELINE_PATH = path.join(__dirname, 'fixtures', 'it-ijazah-en-ar-fr-baseline.json');
const WRITE = process.env.IT_IJAZAH_WRITE_BASELINE === '1';

const sha = (s) => crypto.createHash('sha256').update(s).digest('hex');

async function click(el) {
  fireEvent.click(el);
  await act(async () => {});
}

async function snapshotPage(urlPath, Page) {
  await mountFullPage(urlPath, Page);
  const states = { initial: sha(document.body.innerHTML) };
  const stageHeaders = [...document.querySelectorAll('.cl__stage-header')];
  for (let i = 0; i < stageHeaders.length; i += 1) {
    await click(document.querySelectorAll('.cl__stage-header')[i]);
    states[`stage${i}`] = sha(document.body.innerHTML);
  }
  for (const trigger of document.querySelectorAll('.cl__book-trigger')) await click(trigger);
  states.allBooksOpen = sha(document.body.innerHTML);
  const snap = {
    title: document.title,
    description: headMeta('meta[name="description"]'),
    ogTitle: headMeta('meta[property="og:title"]'),
    ogDescription: headMeta('meta[property="og:description"]'),
    htmlLang: document.documentElement.lang,
    htmlDir: document.documentElement.dir,
    jsonLd: [...document.head.querySelectorAll('script[type="application/ld+json"]')].map((s) => s.textContent),
    stageCount: stageHeaders.length,
    bookCount: document.querySelectorAll('.cl__book-trigger').length,
    states,
  };
  cleanup();
  return snap;
}

useFullPageEnvironment();

async function currentSnapshot() {
  const pages = {};
  for (const lang of ['en', 'ar', 'fr']) {
    pages[lang] = await snapshotPage(lang === 'en' ? '/courses/ijazah' : `/${lang}/courses/ijazah`, CourseIjazah);
  }
  return { baseline: 'origin/main@185fe95', pages };
}

describe('Italian Ijazah batch leaves English, Arabic and French byte-identical', () => {
  if (WRITE) {
    it('writes the EN/AR/FR baseline fixture', async () => {
      fs.mkdirSync(path.dirname(BASELINE_PATH), { recursive: true });
      fs.writeFileSync(BASELINE_PATH, `${JSON.stringify(await currentSnapshot(), null, 2)}
`);
    }, 60000);
    return;
  }

  const baseline = JSON.parse(fs.readFileSync(BASELINE_PATH, 'utf8'));

  it('every EN, AR and FR state of /courses/ijazah (metadata, JSON-LD, full body markup) equals the baseline', async () => {
    const now = await currentSnapshot();
    for (const lang of ['en', 'ar', 'fr']) {
      expect(now.pages[lang], lang).toEqual(baseline.pages[lang]);
    }
  }, 60000);
});
