import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { describe, it, expect, afterEach } from 'vitest';
import { cleanup, fireEvent, act } from '@testing-library/react';
import { useFullPageEnvironment, mountFullPage, headMeta } from './utils/fullPageRender';
import CourseIslamicStudies from '../pages/CourseIslamicStudies';

// Italian Islamic Studies Content Batch: English, Arabic and French
// /courses/islamic-studies must stay byte-for-byte what they were on
// origin/main @ 761453a (before this batch). The baseline fixture was
// generated from that commit with IT_ISLAMIC_WRITE_BASELINE=1 and is compared
// here, never regenerated by a normal run.
//
// Every state is covered, in BOTH hadith modes: the prerender capture
// (navigator.webdriver === true -> the loading placeholder, never a real
// hadith) and a real visitor (webdriver falsy -> today's hadith resolved from
// the fixed test clock). For each: the page as loaded, each curriculum module
// opened in turn, and every book card opened. Per state the SHA-256 of the
// whole <body> markup is recorded, plus title, description, OG tags,
// <html lang/dir> and the JSON-LD.

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BASELINE_PATH = path.join(__dirname, 'fixtures', 'it-islamic-studies-en-ar-fr-baseline.json');
const WRITE = process.env.IT_ISLAMIC_WRITE_BASELINE === '1';

const sha = (s) => crypto.createHash('sha256').update(s).digest('hex');

function setWebdriver(value) {
  Object.defineProperty(window.navigator, 'webdriver', { value, configurable: true });
}

async function click(el) {
  fireEvent.click(el);
  await act(async () => {});
}

async function snapshotPage(urlPath) {
  await mountFullPage(urlPath, CourseIslamicStudies);
  const states = { initial: sha(document.body.innerHTML) };
  const moduleHeaders = [...document.querySelectorAll('.cl__stage-header')];
  for (let i = 0; i < moduleHeaders.length; i += 1) {
    await click(document.querySelectorAll('.cl__stage-header')[i]);
    states[`module${i}`] = sha(document.body.innerHTML);
  }
  for (const trigger of document.querySelectorAll('.cl__book-trigger')) await click(trigger);
  states.allBooksOpen = sha(document.body.innerHTML);
  const snap = {
    title: document.title,
    description: headMeta('meta[name="description"]'),
    ogTitle: headMeta('meta[property="og:title"]'),
    ogDescription: headMeta('meta[property="og:description"]'),
    htmlLang: document.documentElement.lang,
    htmlDir: document.documentElement.dir,
    jsonLd: [...document.head.querySelectorAll('script[type="application/ld+json"]')].map((s) => s.textContent),
    hadithPlaceholder: document.querySelector('[data-testid="hadith-placeholder"]') !== null,
    moduleCount: moduleHeaders.length,
    bookCount: document.querySelectorAll('.cl__book-trigger').length,
    states,
  };
  cleanup();
  return snap;
}

useFullPageEnvironment();

afterEach(() => setWebdriver(undefined));

async function currentSnapshot() {
  const pages = {};
  for (const [mode, webdriver] of [['prerenderCapture', true], ['realVisitor', undefined]]) {
    setWebdriver(webdriver);
    pages[mode] = {};
    for (const lang of ['en', 'ar', 'fr']) {
      pages[mode][lang] = await snapshotPage(lang === 'en' ? '/courses/islamic-studies' : `/${lang}/courses/islamic-studies`);
    }
  }
  return { baseline: 'origin/main@761453a', pages };
}

describe('Italian Islamic Studies batch leaves English, Arabic and French byte-identical', () => {
  if (WRITE) {
    it('writes the EN/AR/FR baseline fixture', async () => {
      fs.mkdirSync(path.dirname(BASELINE_PATH), { recursive: true });
      fs.writeFileSync(BASELINE_PATH, `${JSON.stringify(await currentSnapshot(), null, 2)}\n`);
    }, 120000);
    return;
  }

  const baseline = JSON.parse(fs.readFileSync(BASELINE_PATH, 'utf8'));

  it('every EN, AR and FR state (placeholder and resolved hadith; metadata, JSON-LD, full body markup) equals the baseline', async () => {
    const now = await currentSnapshot();
    for (const mode of ['prerenderCapture', 'realVisitor']) {
      for (const lang of ['en', 'ar', 'fr']) {
        expect(now.pages[mode][lang], `${mode} / ${lang}`).toEqual(baseline.pages[mode][lang]);
      }
    }
    // Sanity: the two modes really differ (placeholder vs resolved hadith).
    expect(baseline.pages.prerenderCapture.en.hadithPlaceholder).toBe(true);
    expect(baseline.pages.realVisitor.en.hadithPlaceholder).toBe(false);
  }, 120000);
});
